//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsGestorDocumentalSoap
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqPublicaDocumento", Namespace="http://tempuri.org/")]
    public partial class ReqPublicaDocumento : object
    {
        
        private wsGestorDocumentalSoap.ImportarArchivo loadfileField;
        
        private long lng_id_carpetaField;
        
        private string str_nombre_carpetaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public wsGestorDocumentalSoap.ImportarArchivo loadfile
        {
            get
            {
                return this.loadfileField;
            }
            set
            {
                this.loadfileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public long lng_id_carpeta
        {
            get
            {
                return this.lng_id_carpetaField;
            }
            set
            {
                this.lng_id_carpetaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string str_nombre_carpeta
        {
            get
            {
                return this.str_nombre_carpetaField;
            }
            set
            {
                this.str_nombre_carpetaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportarArchivo", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.ReqPublicaDocumento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.ImportarArchivoCampo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.ImportarArchivoCampo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.PropertyDocument[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.PropertyDocument))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.ArrayOfAnyType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.InformacionArchivo))]
    public partial class ImportarArchivo : object
    {
        
        private byte[] fileField;
        
        private wsGestorDocumentalSoap.ImportarArchivoCampo[] fieldsField;
        
        private wsGestorDocumentalSoap.PropertyDocument[] propertiesField;
        
        private object policiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public wsGestorDocumentalSoap.ImportarArchivoCampo[] fields
        {
            get
            {
                return this.fieldsField;
            }
            set
            {
                this.fieldsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public wsGestorDocumentalSoap.PropertyDocument[] properties
        {
            get
            {
                return this.propertiesField;
            }
            set
            {
                this.propertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public object policies
        {
            get
            {
                return this.policiesField;
            }
            set
            {
                this.policiesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportarArchivoCampo", Namespace="http://tempuri.org/")]
    public partial class ImportarArchivoCampo : object
    {
        
        private int DocumentTypeIdField;
        
        private int DocumentIdField;
        
        private int FieldIdField;
        
        private string FieldNameField;
        
        private string DataValueField;
        
        private int FieldTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int DocumentTypeId
        {
            get
            {
                return this.DocumentTypeIdField;
            }
            set
            {
                this.DocumentTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int DocumentId
        {
            get
            {
                return this.DocumentIdField;
            }
            set
            {
                this.DocumentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int FieldId
        {
            get
            {
                return this.FieldIdField;
            }
            set
            {
                this.FieldIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FieldName
        {
            get
            {
                return this.FieldNameField;
            }
            set
            {
                this.FieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DataValue
        {
            get
            {
                return this.DataValueField;
            }
            set
            {
                this.DataValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int FieldType
        {
            get
            {
                return this.FieldTypeField;
            }
            set
            {
                this.FieldTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyDocument", Namespace="http://tempuri.org/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.ReqPublicaDocumento))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.ImportarArchivo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.ImportarArchivoCampo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.ImportarArchivoCampo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.PropertyDocument[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.ArrayOfAnyType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(wsGestorDocumentalSoap.InformacionArchivo))]
    public partial class PropertyDocument : object
    {
        
        private string IdField;
        
        private object LocalNameField;
        
        private object LocalNamespaceField;
        
        private string DisplayNameField;
        
        private object QueryNameField;
        
        private object DescriptionField;
        
        private bool QueryableField;
        
        private object PropertyTypeNameField;
        
        private bool InheritedField;
        
        private bool RequiredField;
        
        private bool OrderableField;
        
        private bool OpenChoiceField;
        
        private wsGestorDocumentalSoap.ArrayOfAnyType DefaultValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object LocalName
        {
            get
            {
                return this.LocalNameField;
            }
            set
            {
                this.LocalNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object LocalNamespace
        {
            get
            {
                return this.LocalNamespaceField;
            }
            set
            {
                this.LocalNamespaceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DisplayName
        {
            get
            {
                return this.DisplayNameField;
            }
            set
            {
                this.DisplayNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public object QueryName
        {
            get
            {
                return this.QueryNameField;
            }
            set
            {
                this.QueryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public object Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool Queryable
        {
            get
            {
                return this.QueryableField;
            }
            set
            {
                this.QueryableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public object PropertyTypeName
        {
            get
            {
                return this.PropertyTypeNameField;
            }
            set
            {
                this.PropertyTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool Inherited
        {
            get
            {
                return this.InheritedField;
            }
            set
            {
                this.InheritedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool Required
        {
            get
            {
                return this.RequiredField;
            }
            set
            {
                this.RequiredField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Orderable
        {
            get
            {
                return this.OrderableField;
            }
            set
            {
                this.OrderableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool OpenChoice
        {
            get
            {
                return this.OpenChoiceField;
            }
            set
            {
                this.OpenChoiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public wsGestorDocumentalSoap.ArrayOfAnyType DefaultValue
        {
            get
            {
                return this.DefaultValueField;
            }
            set
            {
                this.DefaultValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    public class ArrayOfAnyType : System.Collections.Generic.List<object>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacionArchivo", Namespace="http://tempuri.org/")]
    public partial class InformacionArchivo : object
    {
        
        private string nombre_archivoField;
        
        private int version_archivoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string nombre_archivo
        {
            get
            {
                return this.nombre_archivoField;
            }
            set
            {
                this.nombre_archivoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int version_archivo
        {
            get
            {
                return this.version_archivoField;
            }
            set
            {
                this.version_archivoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsGestorDocumentalSoap.srvAxentriaSoap")]
    public interface srvAxentriaSoap
    {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento reqloaddocumento del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publicar_archivo", ReplyAction="*")]
        wsGestorDocumentalSoap.publicar_archivoResponse publicar_archivo(wsGestorDocumentalSoap.publicar_archivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/publicar_archivo", ReplyAction="*")]
        System.Threading.Tasks.Task<wsGestorDocumentalSoap.publicar_archivoResponse> publicar_archivoAsync(wsGestorDocumentalSoap.publicar_archivoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento str_nombre_carpeta del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtener_carpeta", ReplyAction="*")]
        wsGestorDocumentalSoap.obtener_carpetaResponse obtener_carpeta(wsGestorDocumentalSoap.obtener_carpetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtener_carpeta", ReplyAction="*")]
        System.Threading.Tasks.Task<wsGestorDocumentalSoap.obtener_carpetaResponse> obtener_carpetaAsync(wsGestorDocumentalSoap.obtener_carpetaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento str_nombre_carpeta del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crear_carpeta", ReplyAction="*")]
        wsGestorDocumentalSoap.crear_carpetaResponse crear_carpeta(wsGestorDocumentalSoap.crear_carpetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/crear_carpeta", ReplyAction="*")]
        System.Threading.Tasks.Task<wsGestorDocumentalSoap.crear_carpetaResponse> crear_carpetaAsync(wsGestorDocumentalSoap.crear_carpetaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento descargar_documentoResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descargar_documento", ReplyAction="*")]
        wsGestorDocumentalSoap.descargar_documentoResponse descargar_documento(wsGestorDocumentalSoap.descargar_documentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/descargar_documento", ReplyAction="*")]
        System.Threading.Tasks.Task<wsGestorDocumentalSoap.descargar_documentoResponse> descargar_documentoAsync(wsGestorDocumentalSoap.descargar_documentoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento str_num_solicitud del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtener_id_documento", ReplyAction="*")]
        wsGestorDocumentalSoap.obtener_id_documentoResponse obtener_id_documento(wsGestorDocumentalSoap.obtener_id_documentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtener_id_documento", ReplyAction="*")]
        System.Threading.Tasks.Task<wsGestorDocumentalSoap.obtener_id_documentoResponse> obtener_id_documentoAsync(wsGestorDocumentalSoap.obtener_id_documentoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_documento", ReplyAction="*")]
        bool eliminar_documento(int int_id_documento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminar_documento", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> eliminar_documentoAsync(int int_id_documento);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento get_name_versionResult del espacio de nombres http://tempuri.org/ no está marcado para convertirse en valor nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_name_version", ReplyAction="*")]
        wsGestorDocumentalSoap.get_name_versionResponse get_name_version(wsGestorDocumentalSoap.get_name_versionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_name_version", ReplyAction="*")]
        System.Threading.Tasks.Task<wsGestorDocumentalSoap.get_name_versionResponse> get_name_versionAsync(wsGestorDocumentalSoap.get_name_versionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publicar_archivoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publicar_archivo", Namespace="http://tempuri.org/", Order=0)]
        public wsGestorDocumentalSoap.publicar_archivoRequestBody Body;
        
        public publicar_archivoRequest()
        {
        }
        
        public publicar_archivoRequest(wsGestorDocumentalSoap.publicar_archivoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publicar_archivoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wsGestorDocumentalSoap.ReqPublicaDocumento reqloaddocumento;
        
        public publicar_archivoRequestBody()
        {
        }
        
        public publicar_archivoRequestBody(wsGestorDocumentalSoap.ReqPublicaDocumento reqloaddocumento)
        {
            this.reqloaddocumento = reqloaddocumento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class publicar_archivoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="publicar_archivoResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsGestorDocumentalSoap.publicar_archivoResponseBody Body;
        
        public publicar_archivoResponse()
        {
        }
        
        public publicar_archivoResponse(wsGestorDocumentalSoap.publicar_archivoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class publicar_archivoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool publicar_archivoResult;
        
        public publicar_archivoResponseBody()
        {
        }
        
        public publicar_archivoResponseBody(bool publicar_archivoResult)
        {
            this.publicar_archivoResult = publicar_archivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtener_carpetaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtener_carpeta", Namespace="http://tempuri.org/", Order=0)]
        public wsGestorDocumentalSoap.obtener_carpetaRequestBody Body;
        
        public obtener_carpetaRequest()
        {
        }
        
        public obtener_carpetaRequest(wsGestorDocumentalSoap.obtener_carpetaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtener_carpetaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str_nombre_carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long lng_id_carpeta;
        
        public obtener_carpetaRequestBody()
        {
        }
        
        public obtener_carpetaRequestBody(string str_nombre_carpeta, long lng_id_carpeta)
        {
            this.str_nombre_carpeta = str_nombre_carpeta;
            this.lng_id_carpeta = lng_id_carpeta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtener_carpetaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtener_carpetaResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsGestorDocumentalSoap.obtener_carpetaResponseBody Body;
        
        public obtener_carpetaResponse()
        {
        }
        
        public obtener_carpetaResponse(wsGestorDocumentalSoap.obtener_carpetaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtener_carpetaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long obtener_carpetaResult;
        
        public obtener_carpetaResponseBody()
        {
        }
        
        public obtener_carpetaResponseBody(long obtener_carpetaResult)
        {
            this.obtener_carpetaResult = obtener_carpetaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crear_carpetaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crear_carpeta", Namespace="http://tempuri.org/", Order=0)]
        public wsGestorDocumentalSoap.crear_carpetaRequestBody Body;
        
        public crear_carpetaRequest()
        {
        }
        
        public crear_carpetaRequest(wsGestorDocumentalSoap.crear_carpetaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class crear_carpetaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lng_id_carpeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string str_nombre_carpeta;
        
        public crear_carpetaRequestBody()
        {
        }
        
        public crear_carpetaRequestBody(long lng_id_carpeta, string str_nombre_carpeta)
        {
            this.lng_id_carpeta = lng_id_carpeta;
            this.str_nombre_carpeta = str_nombre_carpeta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class crear_carpetaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="crear_carpetaResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsGestorDocumentalSoap.crear_carpetaResponseBody Body;
        
        public crear_carpetaResponse()
        {
        }
        
        public crear_carpetaResponse(wsGestorDocumentalSoap.crear_carpetaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class crear_carpetaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long crear_carpetaResult;
        
        public crear_carpetaResponseBody()
        {
        }
        
        public crear_carpetaResponseBody(long crear_carpetaResult)
        {
            this.crear_carpetaResult = crear_carpetaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class descargar_documentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="descargar_documento", Namespace="http://tempuri.org/", Order=0)]
        public wsGestorDocumentalSoap.descargar_documentoRequestBody Body;
        
        public descargar_documentoRequest()
        {
        }
        
        public descargar_documentoRequest(wsGestorDocumentalSoap.descargar_documentoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class descargar_documentoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long lng_id_documento;
        
        public descargar_documentoRequestBody()
        {
        }
        
        public descargar_documentoRequestBody(long lng_id_documento)
        {
            this.lng_id_documento = lng_id_documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class descargar_documentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="descargar_documentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsGestorDocumentalSoap.descargar_documentoResponseBody Body;
        
        public descargar_documentoResponse()
        {
        }
        
        public descargar_documentoResponse(wsGestorDocumentalSoap.descargar_documentoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class descargar_documentoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] descargar_documentoResult;
        
        public descargar_documentoResponseBody()
        {
        }
        
        public descargar_documentoResponseBody(byte[] descargar_documentoResult)
        {
            this.descargar_documentoResult = descargar_documentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtener_id_documentoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtener_id_documento", Namespace="http://tempuri.org/", Order=0)]
        public wsGestorDocumentalSoap.obtener_id_documentoRequestBody Body;
        
        public obtener_id_documentoRequest()
        {
        }
        
        public obtener_id_documentoRequest(wsGestorDocumentalSoap.obtener_id_documentoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtener_id_documentoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int int_tipo_documento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string str_num_solicitud;
        
        public obtener_id_documentoRequestBody()
        {
        }
        
        public obtener_id_documentoRequestBody(int int_tipo_documento, string str_num_solicitud)
        {
            this.int_tipo_documento = int_tipo_documento;
            this.str_num_solicitud = str_num_solicitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtener_id_documentoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtener_id_documentoResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsGestorDocumentalSoap.obtener_id_documentoResponseBody Body;
        
        public obtener_id_documentoResponse()
        {
        }
        
        public obtener_id_documentoResponse(wsGestorDocumentalSoap.obtener_id_documentoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtener_id_documentoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long obtener_id_documentoResult;
        
        public obtener_id_documentoResponseBody()
        {
        }
        
        public obtener_id_documentoResponseBody(long obtener_id_documentoResult)
        {
            this.obtener_id_documentoResult = obtener_id_documentoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_name_versionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_name_version", Namespace="http://tempuri.org/", Order=0)]
        public wsGestorDocumentalSoap.get_name_versionRequestBody Body;
        
        public get_name_versionRequest()
        {
        }
        
        public get_name_versionRequest(wsGestorDocumentalSoap.get_name_versionRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_name_versionRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int int_id_documento;
        
        public get_name_versionRequestBody()
        {
        }
        
        public get_name_versionRequestBody(int int_id_documento)
        {
            this.int_id_documento = int_id_documento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_name_versionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_name_versionResponse", Namespace="http://tempuri.org/", Order=0)]
        public wsGestorDocumentalSoap.get_name_versionResponseBody Body;
        
        public get_name_versionResponse()
        {
        }
        
        public get_name_versionResponse(wsGestorDocumentalSoap.get_name_versionResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_name_versionResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public wsGestorDocumentalSoap.InformacionArchivo get_name_versionResult;
        
        public get_name_versionResponseBody()
        {
        }
        
        public get_name_versionResponseBody(wsGestorDocumentalSoap.InformacionArchivo get_name_versionResult)
        {
            this.get_name_versionResult = get_name_versionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface srvAxentriaSoapChannel : wsGestorDocumentalSoap.srvAxentriaSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class srvAxentriaSoapClient : System.ServiceModel.ClientBase<wsGestorDocumentalSoap.srvAxentriaSoap>, wsGestorDocumentalSoap.srvAxentriaSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public srvAxentriaSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(srvAxentriaSoapClient.GetBindingForEndpoint(endpointConfiguration), srvAxentriaSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public srvAxentriaSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(srvAxentriaSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public srvAxentriaSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(srvAxentriaSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public srvAxentriaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsGestorDocumentalSoap.publicar_archivoResponse wsGestorDocumentalSoap.srvAxentriaSoap.publicar_archivo(wsGestorDocumentalSoap.publicar_archivoRequest request)
        {
            return base.Channel.publicar_archivo(request);
        }
        
        public bool publicar_archivo(wsGestorDocumentalSoap.ReqPublicaDocumento reqloaddocumento)
        {
            wsGestorDocumentalSoap.publicar_archivoRequest inValue = new wsGestorDocumentalSoap.publicar_archivoRequest();
            inValue.Body = new wsGestorDocumentalSoap.publicar_archivoRequestBody();
            inValue.Body.reqloaddocumento = reqloaddocumento;
            wsGestorDocumentalSoap.publicar_archivoResponse retVal = ((wsGestorDocumentalSoap.srvAxentriaSoap)(this)).publicar_archivo(inValue);
            return retVal.Body.publicar_archivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsGestorDocumentalSoap.publicar_archivoResponse> wsGestorDocumentalSoap.srvAxentriaSoap.publicar_archivoAsync(wsGestorDocumentalSoap.publicar_archivoRequest request)
        {
            return base.Channel.publicar_archivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsGestorDocumentalSoap.publicar_archivoResponse> publicar_archivoAsync(wsGestorDocumentalSoap.ReqPublicaDocumento reqloaddocumento)
        {
            wsGestorDocumentalSoap.publicar_archivoRequest inValue = new wsGestorDocumentalSoap.publicar_archivoRequest();
            inValue.Body = new wsGestorDocumentalSoap.publicar_archivoRequestBody();
            inValue.Body.reqloaddocumento = reqloaddocumento;
            return ((wsGestorDocumentalSoap.srvAxentriaSoap)(this)).publicar_archivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsGestorDocumentalSoap.obtener_carpetaResponse wsGestorDocumentalSoap.srvAxentriaSoap.obtener_carpeta(wsGestorDocumentalSoap.obtener_carpetaRequest request)
        {
            return base.Channel.obtener_carpeta(request);
        }
        
        public long obtener_carpeta(string str_nombre_carpeta, long lng_id_carpeta)
        {
            wsGestorDocumentalSoap.obtener_carpetaRequest inValue = new wsGestorDocumentalSoap.obtener_carpetaRequest();
            inValue.Body = new wsGestorDocumentalSoap.obtener_carpetaRequestBody();
            inValue.Body.str_nombre_carpeta = str_nombre_carpeta;
            inValue.Body.lng_id_carpeta = lng_id_carpeta;
            wsGestorDocumentalSoap.obtener_carpetaResponse retVal = ((wsGestorDocumentalSoap.srvAxentriaSoap)(this)).obtener_carpeta(inValue);
            return retVal.Body.obtener_carpetaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsGestorDocumentalSoap.obtener_carpetaResponse> wsGestorDocumentalSoap.srvAxentriaSoap.obtener_carpetaAsync(wsGestorDocumentalSoap.obtener_carpetaRequest request)
        {
            return base.Channel.obtener_carpetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsGestorDocumentalSoap.obtener_carpetaResponse> obtener_carpetaAsync(string str_nombre_carpeta, long lng_id_carpeta)
        {
            wsGestorDocumentalSoap.obtener_carpetaRequest inValue = new wsGestorDocumentalSoap.obtener_carpetaRequest();
            inValue.Body = new wsGestorDocumentalSoap.obtener_carpetaRequestBody();
            inValue.Body.str_nombre_carpeta = str_nombre_carpeta;
            inValue.Body.lng_id_carpeta = lng_id_carpeta;
            return ((wsGestorDocumentalSoap.srvAxentriaSoap)(this)).obtener_carpetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsGestorDocumentalSoap.crear_carpetaResponse wsGestorDocumentalSoap.srvAxentriaSoap.crear_carpeta(wsGestorDocumentalSoap.crear_carpetaRequest request)
        {
            return base.Channel.crear_carpeta(request);
        }
        
        public long crear_carpeta(long lng_id_carpeta, string str_nombre_carpeta)
        {
            wsGestorDocumentalSoap.crear_carpetaRequest inValue = new wsGestorDocumentalSoap.crear_carpetaRequest();
            inValue.Body = new wsGestorDocumentalSoap.crear_carpetaRequestBody();
            inValue.Body.lng_id_carpeta = lng_id_carpeta;
            inValue.Body.str_nombre_carpeta = str_nombre_carpeta;
            wsGestorDocumentalSoap.crear_carpetaResponse retVal = ((wsGestorDocumentalSoap.srvAxentriaSoap)(this)).crear_carpeta(inValue);
            return retVal.Body.crear_carpetaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsGestorDocumentalSoap.crear_carpetaResponse> wsGestorDocumentalSoap.srvAxentriaSoap.crear_carpetaAsync(wsGestorDocumentalSoap.crear_carpetaRequest request)
        {
            return base.Channel.crear_carpetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsGestorDocumentalSoap.crear_carpetaResponse> crear_carpetaAsync(long lng_id_carpeta, string str_nombre_carpeta)
        {
            wsGestorDocumentalSoap.crear_carpetaRequest inValue = new wsGestorDocumentalSoap.crear_carpetaRequest();
            inValue.Body = new wsGestorDocumentalSoap.crear_carpetaRequestBody();
            inValue.Body.lng_id_carpeta = lng_id_carpeta;
            inValue.Body.str_nombre_carpeta = str_nombre_carpeta;
            return ((wsGestorDocumentalSoap.srvAxentriaSoap)(this)).crear_carpetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsGestorDocumentalSoap.descargar_documentoResponse wsGestorDocumentalSoap.srvAxentriaSoap.descargar_documento(wsGestorDocumentalSoap.descargar_documentoRequest request)
        {
            return base.Channel.descargar_documento(request);
        }
        
        public byte[] descargar_documento(long lng_id_documento)
        {
            wsGestorDocumentalSoap.descargar_documentoRequest inValue = new wsGestorDocumentalSoap.descargar_documentoRequest();
            inValue.Body = new wsGestorDocumentalSoap.descargar_documentoRequestBody();
            inValue.Body.lng_id_documento = lng_id_documento;
            wsGestorDocumentalSoap.descargar_documentoResponse retVal = ((wsGestorDocumentalSoap.srvAxentriaSoap)(this)).descargar_documento(inValue);
            return retVal.Body.descargar_documentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsGestorDocumentalSoap.descargar_documentoResponse> wsGestorDocumentalSoap.srvAxentriaSoap.descargar_documentoAsync(wsGestorDocumentalSoap.descargar_documentoRequest request)
        {
            return base.Channel.descargar_documentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsGestorDocumentalSoap.descargar_documentoResponse> descargar_documentoAsync(long lng_id_documento)
        {
            wsGestorDocumentalSoap.descargar_documentoRequest inValue = new wsGestorDocumentalSoap.descargar_documentoRequest();
            inValue.Body = new wsGestorDocumentalSoap.descargar_documentoRequestBody();
            inValue.Body.lng_id_documento = lng_id_documento;
            return ((wsGestorDocumentalSoap.srvAxentriaSoap)(this)).descargar_documentoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsGestorDocumentalSoap.obtener_id_documentoResponse wsGestorDocumentalSoap.srvAxentriaSoap.obtener_id_documento(wsGestorDocumentalSoap.obtener_id_documentoRequest request)
        {
            return base.Channel.obtener_id_documento(request);
        }
        
        public long obtener_id_documento(int int_tipo_documento, string str_num_solicitud)
        {
            wsGestorDocumentalSoap.obtener_id_documentoRequest inValue = new wsGestorDocumentalSoap.obtener_id_documentoRequest();
            inValue.Body = new wsGestorDocumentalSoap.obtener_id_documentoRequestBody();
            inValue.Body.int_tipo_documento = int_tipo_documento;
            inValue.Body.str_num_solicitud = str_num_solicitud;
            wsGestorDocumentalSoap.obtener_id_documentoResponse retVal = ((wsGestorDocumentalSoap.srvAxentriaSoap)(this)).obtener_id_documento(inValue);
            return retVal.Body.obtener_id_documentoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsGestorDocumentalSoap.obtener_id_documentoResponse> wsGestorDocumentalSoap.srvAxentriaSoap.obtener_id_documentoAsync(wsGestorDocumentalSoap.obtener_id_documentoRequest request)
        {
            return base.Channel.obtener_id_documentoAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsGestorDocumentalSoap.obtener_id_documentoResponse> obtener_id_documentoAsync(int int_tipo_documento, string str_num_solicitud)
        {
            wsGestorDocumentalSoap.obtener_id_documentoRequest inValue = new wsGestorDocumentalSoap.obtener_id_documentoRequest();
            inValue.Body = new wsGestorDocumentalSoap.obtener_id_documentoRequestBody();
            inValue.Body.int_tipo_documento = int_tipo_documento;
            inValue.Body.str_num_solicitud = str_num_solicitud;
            return ((wsGestorDocumentalSoap.srvAxentriaSoap)(this)).obtener_id_documentoAsync(inValue);
        }
        
        public bool eliminar_documento(int int_id_documento)
        {
            return base.Channel.eliminar_documento(int_id_documento);
        }
        
        public System.Threading.Tasks.Task<bool> eliminar_documentoAsync(int int_id_documento)
        {
            return base.Channel.eliminar_documentoAsync(int_id_documento);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        wsGestorDocumentalSoap.get_name_versionResponse wsGestorDocumentalSoap.srvAxentriaSoap.get_name_version(wsGestorDocumentalSoap.get_name_versionRequest request)
        {
            return base.Channel.get_name_version(request);
        }
        
        public wsGestorDocumentalSoap.InformacionArchivo get_name_version(int int_id_documento)
        {
            wsGestorDocumentalSoap.get_name_versionRequest inValue = new wsGestorDocumentalSoap.get_name_versionRequest();
            inValue.Body = new wsGestorDocumentalSoap.get_name_versionRequestBody();
            inValue.Body.int_id_documento = int_id_documento;
            wsGestorDocumentalSoap.get_name_versionResponse retVal = ((wsGestorDocumentalSoap.srvAxentriaSoap)(this)).get_name_version(inValue);
            return retVal.Body.get_name_versionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<wsGestorDocumentalSoap.get_name_versionResponse> wsGestorDocumentalSoap.srvAxentriaSoap.get_name_versionAsync(wsGestorDocumentalSoap.get_name_versionRequest request)
        {
            return base.Channel.get_name_versionAsync(request);
        }
        
        public System.Threading.Tasks.Task<wsGestorDocumentalSoap.get_name_versionResponse> get_name_versionAsync(int int_id_documento)
        {
            wsGestorDocumentalSoap.get_name_versionRequest inValue = new wsGestorDocumentalSoap.get_name_versionRequest();
            inValue.Body = new wsGestorDocumentalSoap.get_name_versionRequestBody();
            inValue.Body.int_id_documento = int_id_documento;
            return ((wsGestorDocumentalSoap.srvAxentriaSoap)(this)).get_name_versionAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.srvAxentriaSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.srvAxentriaSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.srvAxentriaSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.55.53/ws_gestor_documental/srvAxentria.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.srvAxentriaSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.55.53/ws_gestor_documental/srvAxentria.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            srvAxentriaSoap,
            
            srvAxentriaSoap12,
        }
    }
}
